### ISSUE TITLE
Plot figures in a grid

### ISSUE THREAD

**Issue by nchelaru** [XanderHorn/autoEDA#4]
Hello!

Thank you so much for such a useful package!

I have been using this package in a Jupyter notebook. The figures from the `autoEDA()` function currently get printed out one after another. As I have quite a few variables, this ends up being a long line of plots.

I have tried to use `par(mfrow=c(r, c))` to get them displayed in a grid, but it doesn't seem to work. Is there a way to get the figures to be displayed in a more compact manner?

If it's any use, this is the code that I am currently using:

```r
library(autoEDA)

par(mfrow=c(8, 2))

autoEDA(df, y = "Churn", IDFeats = NULL, sampleRate = 1,
  outcomeType = "automatic", maxUniques = 15, maxLevels = 25,
  removeConstant = TRUE, removeZeroSpread = TRUE,
  removeMajorityMissing = TRUE, imputeMissing = TRUE, clipOutliers = FALSE,
  minLevelPercentage = 0.025, predictivePower = TRUE,
  outlierMethod = "tukey", lowPercentile = 0.01, upPercentile = 0.99,
  plotCategorical = "groupedBar", plotContinuous = "histogram", bins = 20,
  rotateLabels = FALSE, colorTheme = 1, theme = 2, color = "#26A69A",
  transparency = 1, outputPath = NULL, filename = "ExploratoryPlots",
  verbose = TRUE)
```

Thank you very much!

**Comment by XanderHorn** [comment]
Hi!

Thank you for the feedback and raising this and ofcourse for using the package. 

I see what happened is that I added functionality to return the plots in a list but forgot to include that in the documentation. 

You can apply the below example to your usecase:

`eda <- autoEDA(x = iris, returnPlotList =  T) #stores plots in list` 
`eda$plots$Sepal.Width #call specific plot`

If you want to plot these in a grid you will have to make use of the library called gridExtra since these are ggplot2 objects.

Please let me know if this solves your issue so I can close this.

**Comment by nchelaru** [comment]
Thank you so much for your quick reply, Xander!

Yep, this worked great. Please close this issue.
